import type { Product } from "./types"

// Parse the CSV data into product objects
const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Pure Collagen Cleanser",
    description: "A gentle cleanser enriched with collagen to maintain skin elasticity while cleansing.",
    brand: "COSRX",
    brandTier: "B",
    category: "Cleansers",
    price: 36.22,
    image: "/placeholder.svg?height=400&width=400&text=Collagen+Cleanser",
    inventoryStatus: getInventoryStatus(307, 33),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Maintains elasticity", "Gentle cleansing", "Hydrating"],
    howToUse: "Apply to damp skin, massage gently, and rinse thoroughly with lukewarm water.",
    stats: {
      cogs: 14.83,
      daysOfInventory: 33,
      unitsInStock: 307,
      viewsLastMonth: 3059,
      volumeSoldLastMonth: 185,
    },
  },
  {
    id: "p2",
    name: "Fresh Snail Mucin Cleanser",
    description: "Luxurious cleanser with snail mucin extract for deep hydration and skin repair.",
    brand: "Skinfood",
    brandTier: "A",
    category: "Cleansers",
    price: 76.55,
    image: "/placeholder.svg?height=400&width=400&text=Snail+Mucin+Cleanser",
    inventoryStatus: getInventoryStatus(234, 84),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Deep hydration", "Skin repair", "Gentle cleansing"],
    howToUse: "Massage onto damp skin in circular motions, then rinse thoroughly.",
    stats: {
      cogs: 45.24,
      daysOfInventory: 84,
      unitsInStock: 234,
      viewsLastMonth: 2365,
      volumeSoldLastMonth: 46,
    },
  },
  {
    id: "p3",
    name: "Soothing Hyaluronic Acid Emulsion",
    description: "Lightweight emulsion that delivers intense hydration with hyaluronic acid.",
    brand: "Tony Moly",
    brandTier: "A",
    category: "Emulsions",
    price: 61.24,
    image: "/placeholder.svg?height=400&width=400&text=Hyaluronic+Emulsion",
    inventoryStatus: getInventoryStatus(466, 81),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Deep hydration", "Lightweight formula", "Soothes irritation"],
    howToUse: "Apply to clean skin after toner, gently patting until absorbed.",
    stats: {
      cogs: 30.27,
      daysOfInventory: 81,
      unitsInStock: 466,
      viewsLastMonth: 2579,
      volumeSoldLastMonth: 190,
    },
  },
  {
    id: "p4",
    name: "Glow Niacinamide Mask",
    description: "Brightening sheet mask infused with niacinamide for radiant skin.",
    brand: "Missha",
    brandTier: "A",
    category: "Masks",
    price: 51.91,
    image: "/placeholder.svg?height=400&width=400&text=Niacinamide+Mask",
    inventoryStatus: getInventoryStatus(361, 45),
    isPinned: true,
    createdAt: getRandomDate(),
    benefits: ["Brightens skin", "Evens skin tone", "Reduces dark spots"],
    howToUse: "Apply to clean skin for 15-20 minutes, then pat remaining essence into skin.",
    stats: {
      cogs: 28.68,
      daysOfInventory: 45,
      unitsInStock: 361,
      viewsLastMonth: 4746,
      volumeSoldLastMonth: 227,
    },
  },
  {
    id: "p5",
    name: "Hydra Collagen Serum",
    description: "Intensive serum that boosts skin's collagen production for firmer, plumper skin.",
    brand: "Skinfood",
    brandTier: "B",
    category: "Serums",
    price: 20.92,
    image: "/placeholder.svg?height=400&width=400&text=Collagen+Serum",
    inventoryStatus: getInventoryStatus(70, 47),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Boosts collagen", "Firms skin", "Plumps fine lines"],
    howToUse: "Apply 2-3 drops to clean skin morning and night before moisturizer.",
    stats: {
      cogs: 14.06,
      daysOfInventory: 47,
      unitsInStock: 70,
      viewsLastMonth: 1735,
      volumeSoldLastMonth: 126,
    },
  },
  {
    id: "p6",
    name: "Bright Collagen Mist",
    description: "Refreshing facial mist with collagen to hydrate and firm skin throughout the day.",
    brand: "IOPE",
    brandTier: "B",
    category: "Mists",
    price: 20.92,
    image: "/placeholder.svg?height=400&width=400&text=Collagen+Mist",
    inventoryStatus: getInventoryStatus(172, 34),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Instant hydration", "Refreshes makeup", "Firms skin"],
    howToUse: "Hold bottle 8-10 inches from face and spray evenly. Can be used over makeup.",
    stats: {
      cogs: 9.93,
      daysOfInventory: 34,
      unitsInStock: 172,
      viewsLastMonth: 1857,
      volumeSoldLastMonth: 137,
    },
  },
  {
    id: "p7",
    name: "Calm Hyaluronic Acid Ampoule",
    description: "Concentrated ampoule with hyaluronic acid for intense hydration and calming irritated skin.",
    brand: "Tony Moly",
    brandTier: "C",
    category: "Ampoules",
    price: 14.07,
    image: "/placeholder.svg?height=400&width=400&text=Hyaluronic+Ampoule",
    inventoryStatus: getInventoryStatus(205, 27),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Intense hydration", "Calms irritation", "Strengthens skin barrier"],
    howToUse: "Apply 2-3 drops to clean skin before heavier products.",
    stats: {
      cogs: 7.36,
      daysOfInventory: 27,
      unitsInStock: 205,
      viewsLastMonth: 4552,
      volumeSoldLastMonth: 167,
    },
  },
  {
    id: "p8",
    name: "Hydra Collagen Mask",
    description: "Luxurious sheet mask infused with marine collagen for plump, hydrated skin.",
    brand: "COSRX",
    brandTier: "A",
    category: "Masks",
    price: 61.09,
    image: "/placeholder.svg?height=400&width=400&text=Collagen+Mask",
    inventoryStatus: getInventoryStatus(82, 75),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Intense hydration", "Plumps skin", "Improves elasticity"],
    howToUse: "Apply to clean skin for 15-20 minutes, then pat remaining essence into skin.",
    stats: {
      cogs: 44.26,
      daysOfInventory: 75,
      unitsInStock: 82,
      viewsLastMonth: 2170,
      volumeSoldLastMonth: 219,
    },
  },
  {
    id: "p9",
    name: "Glow Vitamin C Ampoule",
    description: "Potent vitamin C ampoule that brightens skin and fights signs of aging.",
    brand: "Laneige",
    brandTier: "B",
    category: "Ampoules",
    price: 52.08,
    image: "/placeholder.svg?height=400&width=400&text=Vitamin+C+Ampoule",
    inventoryStatus: getInventoryStatus(209, 63),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Brightens skin", "Fights free radicals", "Reduces dark spots"],
    howToUse: "Apply 2-3 drops in the morning before moisturizer and sunscreen.",
    stats: {
      cogs: 24.41,
      daysOfInventory: 63,
      unitsInStock: 209,
      viewsLastMonth: 2949,
      volumeSoldLastMonth: 225,
    },
  },
  {
    id: "p10",
    name: "Radiant Green Tea Serum",
    description: "Antioxidant-rich serum with green tea extract to protect and brighten skin.",
    brand: "Innisfree",
    brandTier: "A",
    category: "Serums",
    price: 59.57,
    image: "/placeholder.svg?height=400&width=400&text=Green+Tea+Serum",
    inventoryStatus: getInventoryStatus(144, 44),
    isPinned: true,
    createdAt: getRandomDate(),
    benefits: ["Antioxidant protection", "Brightens skin", "Reduces inflammation"],
    howToUse: "Apply 2-3 drops to clean skin morning and night before moisturizer.",
    stats: {
      cogs: 25.2,
      daysOfInventory: 44,
      unitsInStock: 144,
      viewsLastMonth: 3351,
      volumeSoldLastMonth: 239,
    },
  },
  {
    id: "p11",
    name: "Fresh Niacinamide Cream",
    description: "Lightweight cream with niacinamide to brighten skin and improve texture.",
    brand: "Mamonde",
    brandTier: "A",
    category: "Moisturizers",
    price: 11.44,
    image: "/placeholder.svg?height=400&width=400&text=Niacinamide+Cream",
    inventoryStatus: getInventoryStatus(169, 89),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Brightens skin", "Improves texture", "Hydrates"],
    howToUse: "Apply a small amount to face and neck morning and night.",
    stats: {
      cogs: 5.57,
      daysOfInventory: 89,
      unitsInStock: 169,
      viewsLastMonth: 3830,
      volumeSoldLastMonth: 335,
    },
  },
  {
    id: "p12",
    name: "Glow Centella Mist",
    description: "Calming facial mist with centella asiatica to soothe and hydrate sensitive skin.",
    brand: "Sulwhasoo",
    brandTier: "B",
    category: "Mists",
    price: 77.89,
    image: "/placeholder.svg?height=400&width=400&text=Centella+Mist",
    inventoryStatus: getInventoryStatus(333, 70),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Soothes irritation", "Reduces redness", "Hydrates"],
    howToUse: "Spray onto face throughout the day as needed, even over makeup.",
    stats: {
      cogs: 34.92,
      daysOfInventory: 70,
      unitsInStock: 333,
      viewsLastMonth: 2589,
      volumeSoldLastMonth: 150,
    },
  },
  {
    id: "p13",
    name: "Pure Snail Mucin Emulsion",
    description: "Lightweight emulsion with snail mucin to repair and hydrate damaged skin.",
    brand: "Etude House",
    brandTier: "A",
    category: "Emulsions",
    price: 68.27,
    image: "/placeholder.svg?height=400&width=400&text=Snail+Mucin+Emulsion",
    inventoryStatus: getInventoryStatus(77, 50),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Repairs skin", "Hydrates", "Improves texture"],
    howToUse: "Apply to clean skin after toner, patting gently until absorbed.",
    stats: {
      cogs: 46.35,
      daysOfInventory: 50,
      unitsInStock: 77,
      viewsLastMonth: 1731,
      volumeSoldLastMonth: 243,
    },
  },
  {
    id: "p14",
    name: "Pure Collagen Toner",
    description: "Hydrating toner with collagen to prep skin and improve elasticity.",
    brand: "Neogen",
    brandTier: "A",
    category: "Toners",
    price: 24.86,
    image: "/placeholder.svg?height=400&width=400&text=Collagen+Toner",
    inventoryStatus: getInventoryStatus(361, 42),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Hydrates", "Improves elasticity", "Preps skin for next steps"],
    howToUse: "Apply to clean skin with a cotton pad or pat in with hands.",
    stats: {
      cogs: 15.97,
      daysOfInventory: 42,
      unitsInStock: 361,
      viewsLastMonth: 2916,
      volumeSoldLastMonth: 80,
    },
  },
  {
    id: "p15",
    name: "Hydra Mugwort Mask",
    description: "Soothing sheet mask with mugwort to calm irritated skin and reduce redness.",
    brand: "Sulwhasoo",
    brandTier: "B",
    category: "Masks",
    price: 22.73,
    image: "/placeholder.svg?height=400&width=400&text=Mugwort+Mask",
    inventoryStatus: getInventoryStatus(324, 77),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Calms irritation", "Reduces redness", "Hydrates"],
    howToUse: "Apply to clean skin for 15-20 minutes, then pat remaining essence into skin.",
    stats: {
      cogs: 13.41,
      daysOfInventory: 77,
      unitsInStock: 324,
      viewsLastMonth: 1115,
      volumeSoldLastMonth: 13,
    },
  },
  {
    id: "p16",
    name: "Silky Propolis Cream",
    description: "Rich cream with propolis extract to nourish and heal damaged skin.",
    brand: "Innisfree",
    brandTier: "A",
    category: "Moisturizers",
    price: 31.3,
    image: "/placeholder.svg?height=400&width=400&text=Propolis+Cream",
    inventoryStatus: getInventoryStatus(189, 23),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Nourishes", "Heals damaged skin", "Strengthens skin barrier"],
    howToUse: "Apply a small amount to face and neck as the last step of your routine.",
    stats: {
      cogs: 20.07,
      daysOfInventory: 23,
      unitsInStock: 189,
      viewsLastMonth: 4711,
      volumeSoldLastMonth: 257,
    },
  },
  {
    id: "p17",
    name: "Youth Centella Cleanser",
    description: "Gentle foaming cleanser with centella asiatica to soothe and purify skin.",
    brand: "Neogen",
    brandTier: "B",
    category: "Cleansers",
    price: 46.73,
    image: "/placeholder.svg?height=400&width=400&text=Centella+Cleanser",
    inventoryStatus: getInventoryStatus(345, 30),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Gentle cleansing", "Soothes irritation", "Purifies skin"],
    howToUse: "Massage onto damp skin, then rinse thoroughly with lukewarm water.",
    stats: {
      cogs: 21.31,
      daysOfInventory: 30,
      unitsInStock: 345,
      viewsLastMonth: 3187,
      volumeSoldLastMonth: 234,
    },
  },
  {
    id: "p18",
    name: "Soothing Ginseng Emulsion",
    description: "Lightweight emulsion with ginseng extract to energize and revitalize tired skin.",
    brand: "Missha",
    brandTier: "C",
    category: "Emulsions",
    price: 40.24,
    image: "/placeholder.svg?height=400&width=400&text=Ginseng+Emulsion",
    inventoryStatus: getInventoryStatus(290, 57),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Energizes skin", "Hydrates", "Improves circulation"],
    howToUse: "Apply to clean skin after toner, patting gently until absorbed.",
    stats: {
      cogs: 26.87,
      daysOfInventory: 57,
      unitsInStock: 290,
      viewsLastMonth: 2939,
      volumeSoldLastMonth: 11,
    },
  },
  {
    id: "p19",
    name: "Youth Mugwort Serum",
    description: "Calming serum with mugwort extract to soothe irritated skin and reduce inflammation.",
    brand: "COSRX",
    brandTier: "A",
    category: "Serums",
    price: 30.39,
    image: "/placeholder.svg?height=400&width=400&text=Mugwort+Serum",
    inventoryStatus: getInventoryStatus(73, 29),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Calms irritation", "Reduces inflammation", "Hydrates"],
    howToUse: "Apply 2-3 drops to clean skin before moisturizer.",
    stats: {
      cogs: 17.07,
      daysOfInventory: 29,
      unitsInStock: 73,
      viewsLastMonth: 435,
      volumeSoldLastMonth: 178,
    },
  },
  {
    id: "p20",
    name: "Calm Centella Serum",
    description: "Soothing serum with centella asiatica to calm sensitive skin and reduce redness.",
    brand: "Benton",
    brandTier: "C",
    category: "Serums",
    price: 52.83,
    image: "/placeholder.svg?height=400&width=400&text=Centella+Serum",
    inventoryStatus: getInventoryStatus(463, 17),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Calms sensitivity", "Reduces redness", "Strengthens skin barrier"],
    howToUse: "Apply 2-3 drops to clean skin morning and night before moisturizer.",
    stats: {
      cogs: 33.93,
      daysOfInventory: 17,
      unitsInStock: 463,
      viewsLastMonth: 4692,
      volumeSoldLastMonth: 145,
    },
  },
  // Adding the new products
  {
    id: "p21",
    name: "Fresh Mugwort Cleanser",
    description: "A gentle cleanser infused with mugwort extract to purify and soothe sensitive skin.",
    brand: "Etude House",
    brandTier: "B",
    category: "Cleansers",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400&text=Mugwort+Cleanser",
    inventoryStatus: getInventoryStatus(120, 40),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Soothes sensitivity", "Gentle cleansing", "Reduces inflammation"],
    howToUse: "Apply to damp skin, massage gently, and rinse thoroughly with lukewarm water.",
    stats: {
      cogs: 15.0,
      daysOfInventory: 40,
      unitsInStock: 120,
      viewsLastMonth: 2100,
      volumeSoldLastMonth: 100,
    },
  },
  {
    id: "p22",
    name: "Brightening Vitamin C Serum",
    description: "Powerful vitamin C serum that brightens skin tone and fades dark spots for a radiant complexion.",
    brand: "IOPE",
    brandTier: "A",
    category: "Serums",
    price: 55.0,
    image: "/placeholder.svg?height=400&width=400&text=Vitamin+C+Serum",
    inventoryStatus: getInventoryStatus(150, 30),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Brightens skin tone", "Fades dark spots", "Antioxidant protection"],
    howToUse: "Apply 3-4 drops to clean skin in the morning, followed by sunscreen.",
    stats: {
      cogs: 28.0,
      daysOfInventory: 30,
      unitsInStock: 150,
      viewsLastMonth: 3500,
      volumeSoldLastMonth: 200,
    },
  },
  {
    id: "p23",
    name: "Hydrating Aloe Vera Gel",
    description: "Lightweight, cooling gel with 92% aloe vera to soothe and hydrate skin after sun exposure.",
    brand: "The Face Shop",
    brandTier: "C",
    category: "Gels",
    price: 18.5,
    image: "/placeholder.svg?height=400&width=400&text=Aloe+Vera+Gel",
    inventoryStatus: getInventoryStatus(300, 60),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Soothes sunburn", "Hydrates without heaviness", "Cooling effect"],
    howToUse: "Apply liberally to face and body as needed, especially after sun exposure.",
    stats: {
      cogs: 9.0,
      daysOfInventory: 60,
      unitsInStock: 300,
      viewsLastMonth: 1800,
      volumeSoldLastMonth: 90,
    },
  },
  {
    id: "p24",
    name: "Soothing Tea Tree Lotion",
    description: "Lightweight lotion with tea tree oil to calm acne-prone skin and reduce inflammation.",
    brand: "Benton",
    brandTier: "B",
    category: "Lotions",
    price: 22.75,
    image: "/placeholder.svg?height=400&width=400&text=Tea+Tree+Lotion",
    inventoryStatus: getInventoryStatus(200, 45),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Controls excess oil", "Calms breakouts", "Reduces redness"],
    howToUse: "Apply a thin layer to clean skin, focusing on areas prone to breakouts.",
    stats: {
      cogs: 11.5,
      daysOfInventory: 45,
      unitsInStock: 200,
      viewsLastMonth: 1600,
      volumeSoldLastMonth: 80,
    },
  },
  {
    id: "p25",
    name: "Revitalizing Ginseng Mask",
    description: "Luxurious sheet mask infused with ginseng extract to energize and revitalize tired, dull skin.",
    brand: "Hera",
    brandTier: "A",
    category: "Masks",
    price: 65.0,
    image: "/placeholder.svg?height=400&width=400&text=Ginseng+Mask",
    inventoryStatus: getInventoryStatus(75, 25),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Energizes skin", "Improves circulation", "Brightens complexion"],
    howToUse: "Apply to clean skin for 15-20 minutes, then pat remaining essence into skin.",
    stats: {
      cogs: 32.5,
      daysOfInventory: 25,
      unitsInStock: 75,
      viewsLastMonth: 2500,
      volumeSoldLastMonth: 120,
    },
  },
  {
    id: "p26",
    name: "Calming Chamomile Toner",
    description: "Gentle, alcohol-free toner with chamomile extract to soothe and balance sensitive skin.",
    brand: "Skinfood",
    brandTier: "B",
    category: "Toners",
    price: 20.0,
    image: "/placeholder.svg?height=400&width=400&text=Chamomile+Toner",
    inventoryStatus: getInventoryStatus(180, 50),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Soothes irritation", "Balances pH", "Preps skin for next steps"],
    howToUse: "Apply to clean skin with a cotton pad or pat in with hands.",
    stats: {
      cogs: 10.0,
      daysOfInventory: 50,
      unitsInStock: 180,
      viewsLastMonth: 1400,
      volumeSoldLastMonth: 60,
    },
  },
  {
    id: "p27",
    name: "Deep Clean Charcoal Foam",
    description: "Deep cleansing foam with activated charcoal to draw out impurities and excess oil.",
    brand: "Missha",
    brandTier: "C",
    category: "Cleansers",
    price: 16.25,
    image: "/placeholder.svg?height=400&width=400&text=Charcoal+Foam",
    inventoryStatus: getInventoryStatus(220, 70),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Deep cleansing", "Removes excess oil", "Unclogs pores"],
    howToUse: "Massage onto damp skin, then rinse thoroughly with lukewarm water.",
    stats: {
      cogs: 8.0,
      daysOfInventory: 70,
      unitsInStock: 220,
      viewsLastMonth: 1200,
      volumeSoldLastMonth: 70,
    },
  },
  {
    id: "p28",
    name: "Moisture Lock Hyaluronic Cream",
    description: "Rich cream with multiple forms of hyaluronic acid to deeply hydrate and plump skin.",
    brand: "Tony Moly",
    brandTier: "A",
    category: "Moisturizers",
    price: 40.0,
    image: "/placeholder.svg?height=400&width=400&text=Hyaluronic+Cream",
    inventoryStatus: getInventoryStatus(130, 55),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Deep hydration", "Plumps fine lines", "Strengthens skin barrier"],
    howToUse: "Apply a small amount to face and neck morning and night.",
    stats: {
      cogs: 20.0,
      daysOfInventory: 55,
      unitsInStock: 130,
      viewsLastMonth: 2300,
      volumeSoldLastMonth: 110,
    },
  },
  {
    id: "p29",
    name: "Ultra Repair Propolis Balm",
    description: "Intensive healing balm with propolis extract to repair damaged skin and strengthen the barrier.",
    brand: "Dr. Jart+",
    brandTier: "B",
    category: "Balms",
    price: 48.0,
    image: "/placeholder.svg?height=400&width=400&text=Propolis+Balm",
    inventoryStatus: getInventoryStatus(160, 35),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Repairs damaged skin", "Strengthens barrier", "Intense hydration"],
    howToUse: "Apply a small amount to areas of concern or all over face as the last step of your routine.",
    stats: {
      cogs: 24.0,
      daysOfInventory: 35,
      unitsInStock: 160,
      viewsLastMonth: 2700,
      volumeSoldLastMonth: 150,
    },
  },
  {
    id: "p30",
    name: "Gentle Rice Water Cleanser",
    description: "Mild, creamy cleanser with rice water extract to brighten and soften skin while cleansing.",
    brand: "Neogen",
    brandTier: "C",
    category: "Cleansers",
    price: 14.5,
    image: "/placeholder.svg?height=400&width=400&text=Rice+Water+Cleanser",
    inventoryStatus: getInventoryStatus(210, 65),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Gentle cleansing", "Brightens skin", "Softens texture"],
    howToUse: "Massage onto damp skin, then rinse thoroughly with lukewarm water.",
    stats: {
      cogs: 7.0,
      daysOfInventory: 65,
      unitsInStock: 210,
      viewsLastMonth: 1100,
      volumeSoldLastMonth: 55,
    },
  },
  {
    id: "p31",
    name: "Radiance Boost Peptide Serum",
    description: "Advanced serum with peptides to firm skin, reduce fine lines, and enhance radiance.",
    brand: "Laneige",
    brandTier: "A",
    category: "Serums",
    price: 62.0,
    image: "/placeholder.svg?height=400&width=400&text=Peptide+Serum",
    inventoryStatus: getInventoryStatus(90, 28),
    isPinned: true,
    createdAt: getRandomDate(),
    benefits: ["Firms skin", "Reduces fine lines", "Enhances radiance"],
    howToUse: "Apply 2-3 drops to clean skin morning and night before moisturizer.",
    stats: {
      cogs: 31.0,
      daysOfInventory: 28,
      unitsInStock: 90,
      viewsLastMonth: 3200,
      volumeSoldLastMonth: 140,
    },
  },
  {
    id: "p32",
    name: "Balancing Green Tea Emulsion",
    description: "Lightweight emulsion with green tea extract to balance oil production and hydrate skin.",
    brand: "Innisfree",
    brandTier: "B",
    category: "Emulsions",
    price: 25.0,
    image: "/placeholder.svg?height=400&width=400&text=Green+Tea+Emulsion",
    inventoryStatus: getInventoryStatus(140, 60),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Balances oil production", "Hydrates", "Soothes irritation"],
    howToUse: "Apply to clean skin after toner, patting gently until absorbed.",
    stats: {
      cogs: 12.5,
      daysOfInventory: 60,
      unitsInStock: 140,
      viewsLastMonth: 1700,
      volumeSoldLastMonth: 85,
    },
  },
  {
    id: "p33",
    name: "Glow Repair Collagen Cream",
    description: "Rich cream with collagen peptides to repair skin damage and restore elasticity.",
    brand: "Etude House",
    brandTier: "A",
    category: "Moisturizers",
    price: 38.0,
    image: "/placeholder.svg?height=400&width=400&text=Collagen+Repair+Cream",
    inventoryStatus: getInventoryStatus(110, 42),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Repairs damage", "Restores elasticity", "Deep hydration"],
    howToUse: "Apply a small amount to face and neck as the last step of your routine.",
    stats: {
      cogs: 19.0,
      daysOfInventory: 42,
      unitsInStock: 110,
      viewsLastMonth: 2000,
      volumeSoldLastMonth: 95,
    },
  },
  {
    id: "p34",
    name: "Nourishing Honey Essence",
    description: "Hydrating essence with honey extract to nourish and revitalize dry, dull skin.",
    brand: "Skinfood",
    brandTier: "C",
    category: "Essences",
    price: 21.0,
    image: "/placeholder.svg?height=400&width=400&text=Honey+Essence",
    inventoryStatus: getInventoryStatus(170, 50),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Nourishes dry skin", "Revitalizes dullness", "Improves texture"],
    howToUse: "Apply a small amount to clean skin after toner, patting gently until absorbed.",
    stats: {
      cogs: 10.5,
      daysOfInventory: 50,
      unitsInStock: 170,
      viewsLastMonth: 1300,
      volumeSoldLastMonth: 75,
    },
  },
  {
    id: "p35",
    name: "Clarifying BHA Toner",
    description: "Exfoliating toner with BHA to clear pores, reduce breakouts, and smooth skin texture.",
    brand: "Missha",
    brandTier: "B",
    category: "Toners",
    price: 27.5,
    image: "/placeholder.svg?height=400&width=400&text=BHA+Toner",
    inventoryStatus: getInventoryStatus(145, 37),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Clears pores", "Reduces breakouts", "Smooths texture"],
    howToUse: "Apply to clean skin with a cotton pad, avoiding the eye area. Start with 2-3 times per week.",
    stats: {
      cogs: 13.5,
      daysOfInventory: 37,
      unitsInStock: 145,
      viewsLastMonth: 2100,
      volumeSoldLastMonth: 100,
    },
  },
  {
    id: "p36",
    name: "Brightening Pearl Mask",
    description: "Luxurious sheet mask infused with pearl extract to brighten and even skin tone.",
    brand: "Sulwhasoo",
    brandTier: "A",
    category: "Masks",
    price: 70.0,
    image: "/placeholder.svg?height=400&width=400&text=Pearl+Mask",
    inventoryStatus: getInventoryStatus(80, 33),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Brightens skin", "Evens tone", "Adds luminosity"],
    howToUse: "Apply to clean skin for 15-20 minutes, then pat remaining essence into skin.",
    stats: {
      cogs: 35.0,
      daysOfInventory: 33,
      unitsInStock: 80,
      viewsLastMonth: 2600,
      volumeSoldLastMonth: 125,
    },
  },
  {
    id: "p37",
    name: "Hydra Boost Water Gel",
    description: "Lightweight, oil-free gel moisturizer that delivers intense hydration without heaviness.",
    brand: "The Face Shop",
    brandTier: "B",
    category: "Gels",
    price: 32.0,
    image: "/placeholder.svg?height=400&width=400&text=Water+Gel",
    inventoryStatus: getInventoryStatus(190, 48),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Oil-free hydration", "Cooling effect", "Absorbs quickly"],
    howToUse: "Apply a small amount to face and neck after cleansing and toning.",
    stats: {
      cogs: 16.0,
      daysOfInventory: 48,
      unitsInStock: 190,
      viewsLastMonth: 1500,
      volumeSoldLastMonth: 90,
    },
  },
  {
    id: "p38",
    name: "Soothing Centella Gel",
    description: "Calming gel with centella asiatica to reduce redness and soothe irritated skin.",
    brand: "Benton",
    brandTier: "A",
    category: "Gels",
    price: 26.0,
    image: "/placeholder.svg?height=400&width=400&text=Centella+Gel",
    inventoryStatus: getInventoryStatus(175, 53),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Reduces redness", "Calms irritation", "Lightweight hydration"],
    howToUse: "Apply a thin layer to clean skin or use as a spot treatment on irritated areas.",
    stats: {
      cogs: 13.0,
      daysOfInventory: 53,
      unitsInStock: 175,
      viewsLastMonth: 1400,
      volumeSoldLastMonth: 60,
    },
  },
  {
    id: "p39",
    name: "Antioxidant Berry Serum",
    description: "Protective serum with berry extracts to shield skin from environmental damage and premature aging.",
    brand: "IOPE",
    brandTier: "C",
    category: "Serums",
    price: 44.0,
    image: "/placeholder.svg?height=400&width=400&text=Berry+Serum",
    inventoryStatus: getInventoryStatus(120, 38),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Protects from environmental damage", "Prevents premature aging", "Brightens skin"],
    howToUse: "Apply 2-3 drops to clean skin in the morning before moisturizer and sunscreen.",
    stats: {
      cogs: 22.0,
      daysOfInventory: 38,
      unitsInStock: 120,
      viewsLastMonth: 2300,
      volumeSoldLastMonth: 110,
    },
  },
  {
    id: "p40",
    name: "Pure Vitamin E Cream",
    description: "Nourishing cream with vitamin E to protect skin from free radicals and improve moisture retention.",
    brand: "Neogen",
    brandTier: "B",
    category: "Moisturizers",
    price: 19.5,
    image: "/placeholder.svg?height=400&width=400&text=Vitamin+E+Cream",
    inventoryStatus: getInventoryStatus(160, 47),
    isPinned: false,
    createdAt: getRandomDate(),
    benefits: ["Protects from free radicals", "Improves moisture retention", "Softens skin"],
    howToUse: "Apply a small amount to face and neck morning and night.",
    stats: {
      cogs: 9.5,
      daysOfInventory: 47,
      unitsInStock: 160,
      viewsLastMonth: 1200,
      volumeSoldLastMonth: 70,
    },
  },
]

// Helper function to determine inventory status based on units and days of inventory
function getInventoryStatus(units: number, days: number): "In Stock" | "Low Stock" | "Out of Stock" {
  if (units < 100) {
    return "Low Stock"
  } else if (days < 20) {
    return "Low Stock"
  } else if (units <= 0) {
    return "Out of Stock"
  } else {
    return "In Stock"
  }
}

// Helper function to generate random dates for the createdAt field
function getRandomDate(): string {
  const start = new Date(2023, 0, 1)
  const end = new Date()
  const randomDate = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
  return randomDate.toISOString()
}

// Simulate API delay
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

// Fetch all products
export async function fetchProducts(): Promise<Product[]> {
  await delay(800) // Simulate network delay
  return [...mockProducts]
}

// Pin a product
export async function pinProduct(productId: string): Promise<void> {
  await delay(500)
  const index = mockProducts.findIndex((p) => p.id === productId)
  if (index !== -1) {
    mockProducts[index].isPinned = true
  }
}

// Unpin a product
export async function unpinProduct(productId: string): Promise<void> {
  await delay(500)
  const index = mockProducts.findIndex((p) => p.id === productId)
  if (index !== -1) {
    mockProducts[index].isPinned = false
  }
}
